version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=ohuser"
      - "POSTGRES_PASSWORD=ohpass"
      - "POSTGRES_DB=ohdb"
  
  web:
    # image: nikolaik/python-nodejs:latest
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - .:/code
    ports:
      - 8880:8000
    command:  >
      sh -c "pip install virtualenvwrapper &&
             pip install -r requirements.txt -r dev-requirements.txt &&
             python /code/manage.py migrate &&
             cnpm install &&
             python /code/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data: